// <auto-generated />
using System;
using AgenticOcr.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgenticOcr.Infrastructure.Migrations
{
    [DbContext(typeof(OcrDbContext))]
    [Migration("20260407213638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgenticOcr.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.EvaluationMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CharacterErrorRate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LayoutScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OcrResultId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Precision")
                        .HasColumnType("double precision");

                    b.Property<double?>("Recall")
                        .HasColumnType("double precision");

                    b.Property<double?>("WordErrorRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OcrResultId")
                        .IsUnique();

                    b.ToTable("EvaluationMetrics");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.MedicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("DrugName")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<bool>("NeedsHumanReview")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OcrResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strength")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OcrResultId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.OcrResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PipelineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimplifiedText")
                        .HasColumnType("text");

                    b.Property<string>("StructuredJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("OcrResults");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.EvaluationMetric", b =>
                {
                    b.HasOne("AgenticOcr.Domain.Entities.OcrResult", "OcrResult")
                        .WithOne("EvaluationMetric")
                        .HasForeignKey("AgenticOcr.Domain.Entities.EvaluationMetric", "OcrResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OcrResult");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.MedicationEntity", b =>
                {
                    b.HasOne("AgenticOcr.Domain.Entities.OcrResult", "OcrResult")
                        .WithMany()
                        .HasForeignKey("OcrResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OcrResult");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.OcrResult", b =>
                {
                    b.HasOne("AgenticOcr.Domain.Entities.Document", "Document")
                        .WithMany("OcrResults")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.Document", b =>
                {
                    b.Navigation("OcrResults");
                });

            modelBuilder.Entity("AgenticOcr.Domain.Entities.OcrResult", b =>
                {
                    b.Navigation("EvaluationMetric");
                });
#pragma warning restore 612, 618
        }
    }
}
